version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
  web:
    build: ./web
    command: realize start --run --no-config
    volumes:
      - ./web:/go/src/app
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_KEY=${GOOGLE_KEY}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - HOST=${HOST}
      - PORT=${PORT}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}

volumes:
  database_data:
    driver: local

